#!/usr/bin/env bash
# 06_multiqc.sh
# Aggregate QC from FastQC, Trim Galore, STAR, featureCounts, and Salmon
# into one MultiQC HTML report.
#
# Usage:
#   bash scripts/06_multiqc.sh
#   bash scripts/06_multiqc.sh --outdir /path/to/custom/outdir

set -euo pipefail

DATA_BASE="${DATA_BASE:-/xdisk/haining/maarowosegbe/RNA-seq}"
OUTDIR="${1:-${DATA_BASE}/results/multiqc}"
SEARCH_DIRS=(
  "${DATA_BASE}/results/fastqc"
  "${DATA_BASE}/results/trimmed"
  "${DATA_BASE}/results/bam"
  "${DATA_BASE}/results/counts"
  "${DATA_BASE}/results/salmon"
  "${DATA_BASE}/logs/"
)

mkdir -p "${OUTDIR}"

echo "=== Running MultiQC ==="
echo "  Searching in: ${SEARCH_DIRS[*]}"

# Filter to directories that actually exist
existing_dirs=()
for d in "${SEARCH_DIRS[@]}"; do
  [[ -d "$d" ]] && existing_dirs+=("$d")
done

micromamba run -n rnaseq_env \
  multiqc \
    "${existing_dirs[@]}" \
    --outdir "${OUTDIR}" \
    --filename "multiqc_report.html" \
    --title "NGS101 RNA-seq Pipeline QC" \
    --comment "Generated by RNA-seq" \
    --export \
    --force \
    2>"${DATA_BASE}/logs/multiqc.log"

echo ""
echo "=== MultiQC complete ==="
echo "  Report: ${OUTDIR}/multiqc_report.html"
echo ""
echo "  Key things to check in the report:"
echo "  1. General statistics table — % aligned, M reads, % duplicates"
echo "  2. FastQC sequence quality — should be >Q30 after trimming"
echo "  3. STAR alignment summary — >70% uniquely mapped is good"
echo "  4. Salmon library type — should auto-detect correctly"
echo ""
echo "Next step:"
echo "  Manual DEG analysis:  Rscript workflow/scripts/deg_analysis.R --help"
echo "  OR full Snakemake run: bash scripts/run_pipeline.sh"
